Разметка
htmlacademy-adaptive/1573711-mishka-26 pull request #2
Opened 2022-07-31 16:16 UTC by loonymax

2022-07-31 16:17 UTC, loonymax commented
Это мой первый раз с БЭМ, буду рада узнать ошибки! Кажется, я перемудрила в форме.

2022-08-02 09:10 UTC, Pakistanka requested changes
В целом хорошо, но слишком усложняешь BEM.

Попробуй упростить. Плюс, для шапки и футера нужно использовать одинаковые классы и писать проще - header и footer

2022-08-02 09:10 UTC, Pakistanka commented on source/catalog.html
> +<html lang="ru">
Может и сюда добавить `class="page"`

2022-08-02 09:10 UTC, Pakistanka commented on source/catalog.html
> +  <header class="catalog-body__header main-header">
А зачем вот этот класс `catalog-body__header`?

2022-08-02 09:10 UTC, Pakistanka commented on source/catalog.html
> +  <footer class="catalog-body__footer footer">
Класс `catalog-body__footer` избыточен

У тебя футер точно будет одинаковый на всех страницах

2022-08-02 09:10 UTC, Pakistanka commented on source/catalog.html
> +    <ul class="footer__social social-list">
Вот тут лучше так
`<ul class="footer__social">
      <li class="footer__item">
        <a class="footer__link" href="#">
          <span class="visually-hidden">Вконтакте</span>
        </a>
      </li>
      <li class="footer__item">
        <a class="footer__link" href="#">
          <span class="visually-hidden">YouTube</span>
        </a>
      </li>`

2022-08-02 09:10 UTC, Pakistanka commented on source/catalog.html
> +    <div class="footer__developed-wrapper developed">
Ну и здесь 
`<div class="footer__developed">
      <span class="footer__text">Разработано</span>
      <a class="footer__link--url" href="https://htmlacademy.ru/">
        <img class="footer__logo" src="" alt="Логотип HTML-Academy.">
      </a>
    </div>`
    
    Соответственно нужно поправить везде.
    
    Не стоит усложнять

2022-08-02 09:10 UTC, Pakistanka commented on source/catalog.html
> +  <section class="catalog-body__modal modal">
Оставь только modal

2022-08-02 09:10 UTC, Pakistanka commented on source/index.html
> +  <header class="index-body__header main-header">
Шапка сайта тоже, чаще всего, однотипная по всему сайту, не стоит усложнять БЕМ

2022-08-02 13:36 UTC, loonymax commented on source/catalog.html
> +  <header class="catalog-body__header main-header">
Поняла, что не нужен, поменяла на `page__header` везде

2022-08-02 13:37 UTC, loonymax commented on source/catalog.html
> +  <footer class="catalog-body__footer footer">
я поменяла на `page__footer` и оставила для стики футера, скажи, если это неправильно

2022-08-02 13:38 UTC, loonymax commented on source/catalog.html
> +    <ul class="footer__social social-list">
Поняла!

2022-08-02 14:49 UTC, merged