Module3 task1
htmlacademy-adaptive/1573711-mishka-26 pull request #3
Opened 2022-08-05 13:47 UTC by loonymax

2022-08-07 08:13 UTC, Pakistanka requested changes
1. Все картинки лучше положить в одну папку, у вас дольше будет модуль по настройке изображения. Все равно придется доставать
2. margin-bottom с дробным значением - плохо

2022-08-07 08:13 UTC, Pakistanka commented on source/catalog.html
> +        <img class="product-card__image" src="./img/catalog-cards/catalog-card-1.jpg" alt="">
Пустые alt? Заполнишь?

2022-08-07 08:13 UTC, Pakistanka commented on source/less/blocks/configurations.less
> +.configurations__fieldset {
Весь этот блок с margin-bottom очень странный. Маленькая разница в значениях и есть дробные. 
Может там выравнивание с помощью сетки делается, а не нижних отступов?

2022-08-07 08:13 UTC, Pakistanka commented on source/less/blocks/main-features.less
> +  &--eco {
Весь блок с картинками. Если у них есть в стайлгайде состояние, то закладывай эти картинки в разметку

2022-08-07 08:13 UTC, Pakistanka commented on source/less/blocks/main-product.less
> +.main-product__price {
Почитай про выравнивание по вертикали и горизонтали во flex. Везде слишком много margin-bottom.

Больше похоже на неумение выравнивать, чем на необходимость - https://yoksel.github.io/flex-cheatsheet/

2022-08-07 08:13 UTC, Pakistanka commented on source/less/blocks/social.less
> +  &--vk {
Эти три иконки должны быть в разметке

2022-08-09 10:00 UTC, loonymax commented on source/catalog.html
> +        <img class="product-card__image" src="./img/catalog-cards/catalog-card-1.jpg" alt="">
Заполнила

2022-08-09 10:01 UTC, loonymax commented on source/less/blocks/main-features.less
> +  &--eco {
Нет состояний, оставляю в стилях

2022-08-09 10:37 UTC, loonymax commented on source/less/blocks/social.less
> +  &--vk {
Сделано!

2022-08-09 10:40 UTC, loonymax commented on source/less/blocks/configurations.less
> +.configurations__fieldset {
Убрала дробные значения, пока что оставила марджины, потому что не знаю, что ставить вместо них, скомпоновала в 1 средний марджин. Позднее по курсу хочу разобраться и в сетках поменять их на что-то другое

2022-08-09 10:41 UTC, loonymax commented on source/less/blocks/main-product.less
> +.main-product__price {
Я пока не знаю, как выравнивать по вертикали без конкретного значения высоты. Могу я пока оставить? Потом при необходимости марджины буду убирать, просто пока не могу сообразить, что вместо них нужно

2022-08-09 19:21 UTC, merged