Module6 task1
htmlacademy-adaptive/1573711-mishka-26 pull request #6
Opened 2022-08-30 07:18 UTC by loonymax

2022-08-31 07:19 UTC, Pakistanka requested changes

2022-08-31 07:19 UTC, Pakistanka commented on source/catalog.html
> +            <img class="product-card__image" src="./img/catalog-card-1-mobile@1x.jpg"
На мобилке зайчик убежал - http://joxi.ru/n2YJEVpikgln1A

2022-09-01 06:25 UTC, loonymax commented on source/catalog.html
> +            <img class="product-card__image" src="./img/catalog-card-1-mobile@1x.jpg"
У меня все в порядке с этим, не знаешь, почему так может быть? http://joxi.ru/82QRgndT85q8jA

2022-09-01 06:26 UTC, loonymax commented on source/catalog.html
> +            <img class="product-card__image" src="./img/catalog-card-1-mobile@1x.jpg"
Кажется, сама поняла, сейчас отправлю на проверку

2022-09-02 12:24 UTC, merged